use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let builtin_root = manifest_dir.join("src").join("builtin_skills");
    println!("cargo:rerun-if-changed={}", builtin_root.display());

    let bundled_skills = discover_bundled_skills(&builtin_root);
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let generated_path = out_dir.join("bundled_skills.generated.rs");
    fs::write(
        &generated_path,
        render_generated_module(&bundled_skills, &builtin_root),
    )
    .expect("generated builtin skills module should be written");
}

fn discover_bundled_skills(root: &Path) -> Vec<BundledSkillFolder> {
    let mut folders = Vec::new();
    let Ok(entries) = fs::read_dir(root) else {
        return folders;
    };

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }

        let id = entry.file_name().to_string_lossy().into_owned();
        let skill_path = path.join("SKILL.md");
        if !skill_path.is_file() {
            continue;
        }

        let mut assets = Vec::new();
        collect_files_recursive(&path, &path, &mut assets);
        if !assets.iter().any(|asset| asset == "SKILL.md") {
            continue;
        }

        folders.push(BundledSkillFolder { id, assets });
    }

    folders.sort_by(|left, right| left.id.cmp(&right.id));
    folders
}

fn collect_files_recursive(root: &Path, base_dir: &Path, files: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if file_type.is_dir() {
            println!("cargo:rerun-if-changed={}", path.display());
            collect_files_recursive(&path, base_dir, files);
            continue;
        }
        if !file_type.is_file() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let Ok(relative) = path.strip_prefix(base_dir) else {
            continue;
        };
        files.push(relative.to_string_lossy().replace('\\', "/"));
    }

    files.sort();
}

fn render_generated_module(skills: &[BundledSkillFolder], builtin_root: &Path) -> String {
    let mut rendered = String::from("// @generated by crates/runtime/build.rs\n");
    rendered.push_str("const BUNDLED_SKILLS: &[BundledSkillDefinition] = &[\n");

    for skill in skills {
        rendered.push_str("    BundledSkillDefinition {\n");
        rendered.push_str(&format!("        id: {:?},\n", skill.id));
        rendered.push_str("        assets: &[\n");
        for asset in &skill.assets {
            let asset_path = builtin_root.join(&skill.id).join(asset);
            let normalized = asset_path.to_string_lossy().replace('\\', "/");
            rendered.push_str("            BundledSkillAsset {\n");
            rendered.push_str(&format!("                relative_path: {:?},\n", asset));
            rendered.push_str(&format!(
                "                content: include_str!({:?}),\n",
                normalized
            ));
            rendered.push_str("            },\n");
        }
        rendered.push_str("        ],\n");
        rendered.push_str("    },\n");
    }

    rendered.push_str("];\n");
    rendered
}

struct BundledSkillFolder {
    id: String,
    assets: Vec<String>,
}
